spring:
  h2:
    console:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000

logging:
  level:
    root: WARN
    kz.skills.elearning: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.flywaydb: INFO
