ALTER TABLE lessons ADD COLUMN video_storage_key VARCHAR(500);
ALTER TABLE lessons ADD COLUMN video_original_filename VARCHAR(255);
ALTER TABLE lessons ADD COLUMN video_content_type VARCHAR(120);
ALTER TABLE lessons ADD COLUMN video_size_bytes BIGINT;
ALTER TABLE lessons ADD COLUMN video_uploaded_at TIMESTAMP;

CREATE TABLE lesson_video_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_lesson_video_uploads_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id),
    CONSTRAINT uk_lesson_video_uploads_lesson UNIQUE (lesson_id),
    CONSTRAINT uk_lesson_video_uploads_object_key UNIQUE (object_key)
);
