CREATE TABLE course_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    current_lesson_id BIGINT,
    status VARCHAR(30) NOT NULL,
    total_steps INTEGER NOT NULL,
    completed_steps INTEGER NOT NULL,
    percent_complete INTEGER NOT NULL,
    attempt_count INTEGER NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    reset_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_course_progress_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT fk_course_progress_student FOREIGN KEY (student_id) REFERENCES platform_users(id),
    CONSTRAINT fk_course_progress_current_lesson FOREIGN KEY (current_lesson_id) REFERENCES lessons(id),
    CONSTRAINT uk_course_progress_student_course UNIQUE (course_id, student_id)
);

CREATE TABLE course_progress_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_course_progress_steps_progress FOREIGN KEY (progress_id) REFERENCES course_progress(id),
    CONSTRAINT fk_course_progress_steps_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id),
    CONSTRAINT uk_course_progress_steps_progress_lesson UNIQUE (progress_id, lesson_id)
);

INSERT INTO course_progress (
    course_id,
    student_id,
    current_lesson_id,
    status,
    total_steps,
    completed_steps,
    percent_complete,
    attempt_count,
    started_at,
    completed_at,
    reset_at,
    created_at,
    updated_at
)
SELECT
    enrollments.course_id,
    enrollments.student_id,
    NULL,
    'NOT_STARTED',
    COUNT(lessons.id),
    0,
    0,
    0,
    NULL,
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM enrollments
LEFT JOIN lessons ON lessons.course_id = enrollments.course_id
GROUP BY enrollments.course_id, enrollments.student_id;

INSERT INTO course_progress_steps (
    progress_id,
    lesson_id,
    step_order,
    status,
    completed_at,
    created_at,
    updated_at
)
SELECT
    progress.id,
    lessons.id,
    lessons.position,
    'NOT_STARTED',
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM course_progress progress
JOIN lessons ON lessons.course_id = progress.course_id;
