-- Optional price set by the teacher (null = free)
ALTER TABLE courses ADD COLUMN price DECIMAL(10, 2);

-- One rating (1-5) per enrolled student per course
CREATE TABLE course_ratings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT   NOT NULL,
    student_id  BIGINT   NOT NULL,
    rating      INTEGER  NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    CONSTRAINT uk_rating_course_student UNIQUE (course_id, student_id),
    CONSTRAINT fk_rating_course  FOREIGN KEY (course_id)  REFERENCES courses(id),
    CONSTRAINT fk_rating_student FOREIGN KEY (student_id) REFERENCES platform_users(id)
);
