-- Immutable audit log for all admin mutations.
-- Rows are append-only: no UPDATE or DELETE should ever be issued against this table.
CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,                          -- NULL if action was performed by the system
    action      VARCHAR(60)  NOT NULL,           -- e.g. COURSE_CREATED, COURSE_PUBLISHED
    entity_type VARCHAR(60)  NOT NULL,           -- e.g. COURSE
    entity_id   VARCHAR(120) NOT NULL,           -- course id or slug
    payload     TEXT,                            -- JSON snapshot of key fields at event time
    occurred_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES platform_users(id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_events_entity ON audit_events (entity_type, entity_id);
CREATE INDEX idx_audit_events_actor  ON audit_events (actor_id);
CREATE INDEX idx_audit_events_time   ON audit_events (occurred_at);
